### ISSUE TITLE
amfi_get_out_of_my_way=1 vs amfi_get_out_of_my_way=0x1

### ISSUE THREAD

**Issue by NewsGuyTor** [w0lfschild/MacForge#30]
## Bug Report

macOS 10.15.3

I disabled AMFI as per the instructions, by setting amfi_get_out_of_my_way=1 as a boot-arg, but the app still reported that AMFI was disabled. I confirmed that the boot arg was active with "nvram -xp"

Then I googled a bit and discovered that all the other sources mentioned that the boot-arg should be 0x1 instead of 1. I tried that and AMFI was disabled.

Perhaps the instructions are incorrect?

**Comment by w0lfschild** [comment]
Copy pasted from Discord:

Important message!

If you are currently using MacForge and have turned off Apple Mobile File Integrity (AMFI) using the command `nvram boot-args="amfi_get_out_of_my_way=1"`

You will not be able to add applications to `System Preferences > Security & Privacy > Privacy`. This can completely prevent some applications form functioning or break critical functionality.

In order to fix this issue, follow the steps below:

1.	open terminal and run the next command
2.	`sudo nvram boot-args=""; sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true`
3.	reboot

An updated version of MacForge should hopefully be coming out soon™️ with a built in warning and automation of these steps.

**Comment by tuxfamily** [comment]
@w0lfschild One hundred thanks for this tip! I lost my day because of that! I was on the way of re-installing the whole system when I remembered that the troubles started right after the install of MacForge.

**Comment by devnoname120** [comment]
@w0lfschild Can't you just do the following instead?

```shell
sudo nvram boot-args="amfi_get_out_of_my_way=1 ipc_control_port_options=0"
```

Non-Apple-signed arm64e DriverKit binaries such as [yabai](https://github.com/koekeishiya/yabai/) won't work though. Adding `-arm64e_preview_abi` to the `boot-args` breaks `amfi_get_out_of_my_way=1` due to a bug in macOS 12.4.
