### ISSUE TITLE
Update button does nothing

### ISSUE THREAD

**Issue by drewauff** [w0lfschild/MacForge#8]
2 Things:

1) I have one app indicating update is available but clicking on update button does nothing.

2) Can't load SafariStand bundle (v11)

**Comment by w0lfschild** [comment]
@drewauff 

1. What plugin are you trying to update?
2. SafariStand doesn't work on Safari versions above 10 I believe : https://github.com/anakinsk/SafariStand
3. If you're on 10.4 or above any plugin required both SIP and AMFI to be off to load into Safari

**Comment by drewauff** [comment]
SpacesRenamer..

We communicated via email quite awhile ago and you said you managed to get SafariStand to inject...

**Comment by w0lfschild** [comment]
Hmm... Yeah I kinda dropped off programming in my spare time for a bit, don't really remember the correspondence. 

I can get plugins to inject into Safari it's more that SafariStand has like no remaining functionality and I'm not going to be the person to update it because I don't even use Safari. Maybe if @anakinsk is still around you could ask them.

I will look into the failing update issue.

**Comment by drewauff** [comment]
ok , did that..but clicking on "get" just results in the button changing to "open"

**Comment by w0lfschild** [comment]
Does it work if you just let it sit for a while? 

It's downloading 8MB each time you click the update button. I need to add some sort of progress indicator now that MacForge supports apps and themes.

**Comment by drewauff** [comment]
nope .. does nothing....

**Comment by w0lfschild** [comment]
Sorry for the long wait but I think I've actually figured out the problem now. It had to do with the plugin folder permissions.

Try version [0.9.11](https://github.com/w0lfschild/app_updates/raw/master/MacForge/MacForge.zip)
